spring:
  servlet: #文件上传配置
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: MySentinel
  #sentinel
  cloud:
    sentinel:
      eager: true
      transport:
        port: 8720
        dashboard: 192.168.135.142:8780
        heartbeat-interval-ms: 500
  #数据库设置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: chen1995210
    url: jdbc:mysql://localhost:3306/angel
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.angel.servie.*
      #表情支持
      connection-init-sqls: set names utf8mb4

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: admin
        login-password: admin
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        #deny: 127.0.0.1

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true

#fastdfs 配置
fdfs:
  connect-timeout: 600
  so-timeout: 1500
  tracker-list: 192.168.135.146:22122
  thumb-image:
    height: 200
    width: 200
